name: Deploy frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-one: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sabsush/docker-react -f Dockerfile.dev
      - run: docker run -e CI=true sabsush/docker-react npm test
